"""Safe construction of the few Cypher fragments that cannot be parameterised.

HydraDB accepts composite parameters *only* as an `UNWIND` source. Everywhere
else -- most importantly `algo.MSpaths`'s `sourceValues` / `targetValues` -- a
list must appear as an inline literal in the query text.

That is a string-injection surface, and the values reaching it are package
names, symbol names and file paths harvested from npm and from source files we
did not write. So all inlining funnels through this module, values are validated
against a strict allowlist before quoting, and nothing else in Adit builds
Cypher by concatenation.
"""

from __future__ import annotations

import re

# Canonical keys are machine-generated by adit.graph.ids, but their *inputs*
# come from registry metadata and parsed source. This pattern covers every
# character those builders can legitimately emit and nothing else -- notably no
# quotes, backslashes, braces, newlines, or comment sequences.
#: `<` and `>` are permitted because Adit's own synthetic symbol names use them
#: (`<module>`, `<anon@42>`, `<side-effect:./x>`). Neither character has any
#: meaning inside a single-quoted Cypher string literal, and neither can occur
#: in a JavaScript identifier -- which is exactly why they were chosen: a
#: synthetic name can never collide with a real declaration.
_SAFE_KEY = re.compile(r"^[A-Za-z0-9_./:@#^~+\-\[\]|<>]{1,512}$")

_SAFE_IDENT = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,63}$")


class UnsafeCypherValue(ValueError):
    """A value was rejected before it could reach the query text."""


def safe_key(value: str) -> str:
    """Validate a canonical key destined for inline use, and quote it.

    Rejects rather than escapes. An escaping bug is invisible; a rejection is a
    stack trace. Given keys are generated by us from constrained inputs, a
    rejection means something upstream is wrong and we want to hear about it.
    """
    if not isinstance(value, str):
        raise UnsafeCypherValue(f"expected str, got {type(value).__name__}")
    if not _SAFE_KEY.match(value):
        raise UnsafeCypherValue(f"key not representable inline: {value!r}")
    return f"'{value}'"


def safe_ident(value: str) -> str:
    """Validate a label or relationship type for inline use (never quoted)."""
    if not _SAFE_IDENT.match(value or ""):
        raise UnsafeCypherValue(f"not a valid identifier: {value!r}")
    return value


def string_list(values: list[str]) -> str:
    """Render a Python list of keys as an inline Cypher string list."""
    if not values:
        raise UnsafeCypherValue("refusing to inline an empty list")
    return "[" + ", ".join(safe_key(v) for v in values) + "]"


def int_list(values: list[int]) -> str:
    """Render a Python list of ints as an inline Cypher integer list."""
    if not values:
        raise UnsafeCypherValue("refusing to inline an empty list")
    for v in values:
        if not isinstance(v, int) or isinstance(v, bool):
            raise UnsafeCypherValue(f"expected int, got {v!r}")
    return "[" + ", ".join(str(v) for v in values) + "]"


def mspaths(
    *,
    source_label: str,
    source_keys: list[str],
    target_keys: list[str],
    rel_types: list[str],
    direction: str = "outgoing",
    max_len: int = 12,
    path_count: int = 3,
    result_limit: int = 500,
    pairwise: bool = False,
) -> str:
    """Build an `algo.MSpaths` call.

    This is the only route to a renderable path: plain `RETURN` cannot project
    `nodes(p)` or `length(p)`, while MSpaths yields a fully hydrated Path with
    node properties intact. It also resolves every (source, target) pair in one
    server-side call instead of `len(sources) * len(targets)` round trips.

    Matching is on the string `key` property, because MSpaths requires
    `sourceValues` to be a list of strings while node `id` must be an integer.
    """
    if direction not in {"outgoing", "incoming", "both"}:
        raise UnsafeCypherValue(f"bad direction: {direction!r}")
    for n, v in (("max_len", max_len), ("path_count", path_count),
                 ("result_limit", result_limit)):
        if not isinstance(v, int) or v < 1:
            raise UnsafeCypherValue(f"{n} must be a positive int, got {v!r}")

    rels = "[" + ", ".join(f"'{safe_ident(r)}'" for r in rel_types) + "]"
    return (
        "CALL algo.MSpaths({"
        f"sourceLabel: '{safe_ident(source_label)}', sourceProperty: 'key', "
        f"sourceValues: {string_list(source_keys)}, "
        f"targetValues: {string_list(target_keys)}, "
        f"relTypes: {rels}, relDirection: '{direction}', "
        f"maxLen: {max_len}, pathCount: {path_count}, "
        f"resultLimit: {result_limit}"
        + (", pairwise: true" if pairwise else "")
        + "}) YIELD path RETURN path"
    )
